version: '3.3'
services:
  mongodb:
    image: mongo:3.6
    container_name: healfitmongodb
    ports:
      - '27017:27017'
    command: --profile=1 --slowms=1
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: healfit
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
